# ===================================================================
# Global Configuration File v2
#
# This file defines the foundational settings, defaults, and
# region-specific overrides for the entire network automation system.
# ===================================================================

# --- Data for Validation and Interactive Prompts ---
validation_data:
  vendors:
    - Cisco
    - dell
    - Juniper
    - Arista
    - Fortinet
    - HPE Aruba
    - Ubiquiti
  template_styles:
    - access_switch
    - core_switch
    - distribution_switch
    - router
    - firewall

# --- Default Device Capabilities ---
# These flags determine which configuration blocks are rendered.
# They can be overridden in device-specific YAML files.
default_capabilities:
  supports_vlan_interface: true
  supports_loopback: false
  supports_enable_password: true
  supports_SNMP: true
  supports_AAA: true
  supports_ssh: true
  supports_https: true
  supports_telnet: false
  supports_ospf: false
  supports_tacacs: true
  supports_radius: false
  supports_acl: true
  supports_logging: true
  supports_ntp: true
  supports_dhcp: false
  supports_bgp: true

# --- Global Best Practice Settings ---
base_commands:
  - "service password-encryption"
  - "no ip http server"
  - "no ip http secure-server"
  - "ip ssh version 2"

banner_text: |
  *****************************************************************
  * This system is for authorized use only.                       *
  * All activities on this system are logged and monitored.       *
  * Disconnect immediately if you are not an authorized user.     *
  * Hostname: [HOSTNAME]                                          *
  *****************************************************************

fallback_user:
  username: "localadmin"
  privilege: 15
  # Password for this user should be set via environment variable
  # or prompted for interactively by the Python script.

# --- Default Configurations for Advanced Features ---
# These serve as a base that can be merged with device-specific settings.
default_configs:
  logging:
    hosts:
      - "10.0.0.10" # Default syslog server
    level: informational

  acl:
    - name: Management_access
      rules:
        - action: permit
          protocol: ip
          dst: 192.0.2.10
        - action: permit
          protocol: ip
          dst: 192.0.2.11
        - action: deny
          protocol: ip
          dst: any

  bgp:
    asn: 65001
    router_id: 10.0.0.1
    networks:
      - "10.1.0.0 mask 255.255.0.0"
      - "10.2.0.0 mask 255.255.0.0"
    neighbors:
      - ip: 192.0.2.1
        remote_as: 65002
        description: Connection to ISP1
        update_source: Loopback0
        next_hop_self: true
        soft_reconfig: true
        route_map_in: RM-IN
        route_map_out: RM-OUT

# --- Region-Specific Overrides ---
# These settings will be applied based on the 'region' key in
# the device-specific YAML file.
regions:
  eu:
    ntp:
      servers:
        - 0.eu.pool.ntp.org
        - 1.eu.pool.ntp.org
    tacacs:
      servers:
        - 192.0.2.200
    dns:
      domain_name: eu.corp.com
      servers:
        - 8.8.8.8
        - 8.8.4.4
  ap:
    ntp:
      servers:
        - 0.asia.pool.ntp.org
        - 1.asia.pool.ntp.org
    tacacs:
      servers:
        - 203.0.113.10
    dns:
      domain_name: ap.corp.com
      servers:
        - 1.1.1.1
        - 1.0.0.1
  am:
    ntp:
      servers:
        - 0.us.pool.ntp.org
        - 1.us.pool.ntp.org
    tacacs:
      servers:
        - 198.51.100.10
    dns:
      domain_name: am.corp.com
      servers:
        - 9.9.9.9
        - 149.112.112.112
