acl:
  - name: Management_access
    rules:
      - action: permit
        protocol: ip
        dst: 192.0.2.10
      - action: permit
        protocol: ip
        dst: 192.0.2.11
      - action: deny
        protocol: ip
        dst: any

logging:
  hosts:
    - "10.x.x.x"
  level: informational

ospf:
  process_id: 1
  networks:
    - "10.x.x.x 0.0.0.255 area 0"

stp:
  enabled: true
  core_priority: 4096
  bridge_priority: 32768

regions:
  eu:
    ntp:
      servers:
        - 0.eu.pool.ntp.org
        - 1.eu.pool.ntp.org
    tacacs:
      servers:
        - 192.0.2.200
    dns:
      domain_name: eu.corp.com
      servers:
        - 8.8.8.8
        - 8.8.4.4
  ap:
    ntp:
      servers:
        - 0.asia.pool.ntp.org
        - 1.asia.pool.ntp.org
    tacacs:
      servers:
        - 203.0.113.10
    dns:
      domain_name: ap.corp.com
      servers:
        - 1.1.1.1
        - 1.0.0.1
  am:
    ntp:
      servers:
        - 0.us.pool.ntp.org
        - 1.us.pool.ntp.org
    tacacs:
      servers:
        - 198.51.100.10
    dns:
      domain_name: am.corp.com
      servers:
        - 9.9.9.9
        - 149.112.112.112

interface_vlans:
  - id: 10
    description: Users
    ip_address: "10.x.x.x"
    subnet_mask: "255.255.255.0"
  - id: 20
    description: Servers
    ip_address: "10.x.x.x"
    subnet_mask: "255.255.255.0"
  - id: 30
    description: Management
    ip_address: "10.x.x.x"
    subnet_mask: "255.255.255.0"
  - id: 40
    description: VoIP
    ip_address: "10.x.x.x"
    subnet_mask: "255.255.255.0"
  - id: 50
    description: Wireless
    ip_address: "10.x.x.x"
    subnet_mask: "255.255.255.0"
  - id: 60
    description: Parking_Lot
    ip_address: "10.x.x.x"
    subnet_mask: "255.255.255.0"