vendor:
  - Cisco
  - Juniper
  - Arista
  - HP
  - Extreme
  - Huawei
  - Brocade
  - Netgear
  - MikroTik
  - TP-Link
  - Zyxel
  - Allied Telesis
  - Avaya
  - Alcatel-Lucent
  - D-Link
  - Linksys
  - Ubiquiti
  - Edgecore
  - Mellanox
  - Ruckus
  - Cisco Meraki
  - Fortinet
  - Palo Alto Networks
  - HPE Aruba
  - Dell EMC Networking

template_style:
  - access_switch
  - core_switch
  - distribution_switch
  - router
  - firewall
  - wireless_controller

interface_prefix:
  - TenGigabitEthernet
  - GigabitEthernet
  - port-channel
  - Ethernet
  - FastEthernet
  - TenGigE
  - GigE
  - Te
  - Gi
  - Fa
  - Po
  - port
  - xe-

supports_vlan_interface: true
supports_loopback: false
supports_enable_password: true
supports_SNMP: true
supports_AAA: true
supports_ssh: true
supports_https: true
supports_telnet: false
supports_ospf: false
supports_tacacs: true
supports_radius: false
supports_acl: true
supports_logging: true
supports_ntp: true
supports_dhcp: false
supports_bgp: true

acl:
  - name: Management_access
    rules:
      - action: permit
        protocol: ip
        dst: 192.0.2.10
      - action: permit
        protocol: ip
        dst: 192.0.2.11
      - action: deny
        protocol: ip
        dst: any

logging:
  hosts:
    - "10.x.x.x"
  level: informational

ospf:
  process_id: 1
  networks:
    - "10.x.x.x 0.0.0.255 area 0"

bgp:
  asn: 65001
  router_id: 10.0.0.1
  networks:
    - "10.1.0.0 mask 255.255.0.0"
    - "10.2.0.0 mask 255.255.0.0"
  neighbors:
    - ip: 192.0.2.1
      remote_as: 65002
      description: Connection to ISP1
      update_source: Loopback0
      next_hop_self: true
      soft_reconfig: true
      route_map_in: RM-IN
      route_map_out: RM-OUT
    - ip: 192.0.2.2
      remote_as: 65003
      description: Connection to ISP2
      update_source: Loopback0
      next_hop_self: true
      soft_reconfig: false
  prefix_lists:
    - name: PL-IN
      description: Permit internal prefixes
      rules:
        - action: permit
          prefix: 10.0.0.0/8
        - action: deny
          prefix: 0.0.0.0/0
    - name: PL-OUT
      description: Only advertise specific ranges
      rules:
        - action: permit
          prefix: 10.1.0.0/16
  route_maps:
    - name: RM-IN
      description: Apply inbound filters
      entries:
        - sequence: 10
          action: permit
          match: prefix-list PL-IN
        - sequence: 20
          action: deny
    - name: RM-OUT
      description: Apply outbound filters
      entries:
        - sequence: 10
          action: permit
          match: prefix-list PL-OUT

regions:
  eu:
    ntp:
      servers:
        - 0.eu.pool.ntp.org
        - 1.eu.pool.ntp.org
    tacacs:
      servers:
        - 192.0.2.200
    dns:
      domain_name: eu.corp.com
      servers:
        - 8.8.8.8
        - 8.8.4.4
  ap:
    ntp:
      servers:
        - 0.asia.pool.ntp.org
        - 1.asia.pool.ntp.org
    tacacs:
      servers:
        - 203.0.113.10
    dns:
      domain_name: ap.corp.com
      servers:
        - 1.1.1.1
        - 1.0.0.1
  am:
    ntp:
      servers:
        - 0.us.pool.ntp.org
        - 1.us.pool.ntp.org
    tacacs:
      servers:
        - 198.51.100.10
    dns:
      domain_name: am.corp.com
      servers:
        - 9.9.9.9
        - 149.112.112.112