# ===================================================================
# Golden Template for Access Switch
#
# This file defines the exact standard configuration for an access switch,
# including all VLANs, interfaces, and default settings.
# ===================================================================

# --- Default Spanning Tree Settings ---
stp:
  enabled: true
  bridge_priority: 32768

# --- Default Capabilities ---
supports_loopback: false

# --- Default DNS and Logging (can be overridden) ---
dns:
  servers:
    - "8.8.8.8"  # Enter DNS server IP addresses here
    - "1.1.1.1"
logging:
  hosts:
    - "10.10.0.50"  # Enter log server IP address here
  level: informational

# --- Default Time Synchronization (NTP) ---
# ntp:
#   servers:
#     - "pool.ntp.org"

# --- Default SNMP (keys must be provided in the input file) ---
snmp:
  location: "Default Location"
  contact: "noc@example.com"

# --- Default VLANs ---
vlans:
  - id: 10
    name: Users
  - id: 20
    name: Servers
  - id: 30
    name: Management
  - id: 50
    name: Wireless
  - id: 999
    name: Parking-Lot

# --- Default Interface Configuration ---
interfaces:
  - name: "TenGigabitEthernet 1/0/1"
    description: "Access Port - Users VLAN"
    mode: access
    vlan: 10
    enabled: true
    spanningtree: "portfast"
  - name: "TenGigabitEthernet 1/0/2"
    description: "Trunk to Wireless AP"
    mode: trunk
    allowed_vlans: "10,50"
    enabled: true
    spanningtree: "bpduguard_enable"
  - name: "TenGigabitEthernet 1/0/48"
    description: "Uplink to Core"
    mode: trunk
    allowed_vlans: "10,20,30,50"
    enabled: true
    spanningtree: "none"
  - name: "TenGigabitEthernet 1/0/3"
    description: "Access Port - VoIP Phones"
    mode: access
    vlan: 10 # Assuming data vlan is 10, voice vlan would be handled by voice vlan command
    enabled: true
    spanningtree: "portfast"
    poe: "enable" # Use 'poe: enable' or similar based on template
  - name: "TenGigabitEthernet 1/0/24"
    description: "Parking Lot"
    mode: access
    vlan: 999
    enabled: false
    spanningtree: "portfast"

# --- Default SVI (Management Interface) ---
vlan_interfaces:
  - id: 30
    name: "Management Interface"
    ip_address: "10.10.30.5" # Note: This IP will be the same for all devices!
    subnet_mask: "255.255.255.0"
