# ===================================================================
# Golden Template för Core Switch
#
# Denna fil definierar exakt hur en standard core-switch ska se ut,
# inklusive VLANs, L3-interface, loopbacks och routing-protokoll.
# ===================================================================

# --- Standardkapabiliteter ---
supports_vlan_interface: true
supports_loopback: true
supports_ospf: true
supports_bgp: true

# --- Standardinställningar för Spanning Tree ---
# Låg prioritet för att säkerställa att denna switch blir root bridge.
stp:
  enabled: true
  bridge_priority: 4096

# --- Standard-VLANs som ska finnas på core-nivå ---
vlans:
  - id: 10
    name: Users
  - id: 20
    name: Servers
  - id: 30
    name: Management
  - id: 40
    name: VoIP
  - id: 50
    name: Wireless
  - id: 100
    name: Core-Transit

# --- Standard Interface-konfiguration ---
# Exempel på vanliga interface-typer på en core-switch
interfaces:
  - name: "TenGigabitEthernet 1/0/1"
    description: "L3 Länk till Router-01"
    mode: none # Indikerar ett L3-interface
    ip_address: "10.100.0.1"
    subnet_mask: "255.255.255.252"
    enabled: true

  - name: "TenGigabitEthernet 1/0/2"
    description: "L3 Länk till Router-02"
    mode: none
    ip_address: "10.100.0.5"
    subnet_mask: "255.255.255.252"
    enabled: true

  - name: "TenGigabitEthernet 1/0/10"
    description: "Trunk till Distribution-Switch-01"
    mode: trunk
    allowed_vlans: "10,20,30,40,50"
    enabled: true
    spanningtree: "none" # BPDU-skydd är oftast avstängt mellan switchar

# --- Standard Loopback-interface ---
# Används ofta för router-ID och management
loopbacks:
  - id: 0
    description: "Router-ID och Management"
    # Den unika IP-adressen sätts i den specifika enhetsfilen
    ip_address: "10.0.0.1"
    subnet_mask: "255.255.255.255"

# --- Standard Switched Virtual Interfaces (SVIs) ---
# Dessa agerar som default gateway för sina respektive VLAN
vlan_interfaces:
  - id: 10
    description: "GW Users VLAN"
    ip_address: "10.10.10.1"
    subnet_mask: "255.255.255.0"
  - id: 20
    description: "GW Servers VLAN"
    ip_address: "10.10.20.1"
    subnet_mask: "255.255.255.0"
  - id: 30
    description: "GW Management VLAN"
    ip_address: "10.10.30.1"
    subnet_mask: "255.255.255.0"
