# ===================================================================
# Golden Template for Core Switch
#
# This file defines the exact standard configuration for a core switch,
# including VLANs, L3 interfaces, loopbacks, and routing protocols.
# ===================================================================

# --- Default Capabilities ---
supports_vlan_interface: true
supports_loopback: true
supports_ospf: true
supports_bgp: true

# --- Default Spanning Tree Settings ---
# Low priority to ensure this switch becomes the root bridge.
stp:
  enabled: true
  bridge_priority: 4096

# --- Default VLANs to be present at the core level ---
vlans:
  - id: 10
    name: Users
  - id: 20
    name: Servers
  - id: 30
    name: Management
  - id: 40
    name: VoIP
  - id: 50
    name: Wireless
  - id: 100
    name: Core-Transit

# --- Default Interface Configuration ---
# Examples of common interface types on a core switch
interfaces:
  - name: "TenGigabitEthernet 1/0/1"
    description: "L3 Link to Router-01"
    mode: none # Indicates an L3 interface
    ip_address: "10.100.0.1"
    subnet_mask: "255.255.255.252"
    enabled: true

  - name: "TenGigabitEthernet 1/0/2"
    description: "L3 Link to Router-02"
    mode: none
    ip_address: "10.100.0.5"
    subnet_mask: "255.255.255.252"
    enabled: true

  - name: "TenGigabitEthernet 1/0/10"
    description: "Trunk to Distribution-Switch-01"
    mode: trunk
    allowed_vlans: "10,20,30,40,50"
    enabled: true
    spanningtree: "none" # BPDU guard is usually disabled between switches

# --- Default Loopback Interface ---
# Often used for router-ID and management
loopbacks:
  - id: 0
    description: "Router-ID and Management"
    # The unique IP address is set in the specific device file
    ip_address: "10.0.0.1"
    subnet_mask: "255.255.255.255"

# --- Default Switched Virtual Interfaces (SVIs) ---
# These act as the default gateway for their respective VLANs
vlan_interfaces:
  - id: 10
    description: "GW Users VLAN"
    ip_address: "10.10.10.1"
    subnet_mask: "255.255.255.0"
  - id: 20
    description: "GW Servers VLAN"
    ip_address: "10.10.20.1"
    subnet_mask: "255.255.255.0"
  - id: 30
    description: "GW Management VLAN"
    ip_address: "10.10.30.1"
    subnet_mask: "255.255.255.0"
