vendor: Cisco, Juniper, Arista, Fortinet, Dell EMC Networking
template_style: Core_switch
interface_prefix: TenGigabitEthernet, GigabitEthernet, port-channel, Ethernet, FastEthernet, TenGigabitEthernet,
  GigabitEthernet, TenGigE, GigE, Te, Gi, Fa, Po, port, xe-
supports_vlan_interface: true
supports_loopback: true
supports_enable_password: true
supports_SNMP: true
supports_AAA: true
supports_ssh: true
supports_https: true
supports_telnet: false
supports_ospf: true
supports_tacacs: true
supports_radius: false
supports_acl: true
supports_logging: true
supports_ntp: true
supports_dhcp: false
supports_bgp: true

stp:
  enabled: true
  core_priority: 4096

interfaces:
  - name: Access_VLAN_Port
    description: Access VLAN port
    mode: access
    vlan: 10
    no_shutdown: true
    spanningtree: portfast
    EEE: False

  - name: Trunk_to_AP
    description: Trunk to AP
    mode: trunk
    allowed_vlans: 10,20
    no_shutdown: true
    spanningtree: true
    EEE: False

  - name: Uplink_to_Core
    description: Uplink to Core
    mode: trunk
    allowed_vlans: 10,20,30
    no_shutdown: true
    spanningtree: none
    EEE: False

  - name: Parking_Lot
    description: Parking Lot
    mode: access
    vlan: 999
    no_shutdown: false
    spanningtree: none
    EEE: False

loopbacks:
  - id: 0
    description: Loopback Interface
    ip_address: 10.0.0.1
    subnet_mask: 255.255.255.255

vlan_interfaces:
  - id: 10
    description: Users VLAN
    ip_address: 10.x.x.x
    subnet_mask: 255.255.255.0
  - id: 20
    description: Servers VLAN
    ip_address: 10.x.x.x
    subnet_mask: 255.255.255.0
  - id: 30
    description: Management VLAN
    ip_address: 10.x.x.x
    subnet_mask: 255.255.255.0
  - id: 40
    description: VoIP VLAN
    ip_address: 10.x.x.x
    subnet_mask: 255.255.255.0
  - id: 50
    description: Wireless VLAN
    ip_address: 10.x.x.x
    subnet_mask: 255.255.255.0
  - id: 60
    description: Parking Lot VLAN
    ip_address: 10.x.x.x
    subnet_mask: 255.255.255.0