# ===================================================================
# Golden Template for FortiGate Firewall
#
# This file defines a standard configuration for a firewall,
# including interfaces, zones, addresses, and basic policies.
# ===================================================================

# --- Default Capabilities ---
supports_vlan_interface: true
supports_loopback: true
supports_ospf: true
supports_bgp: true

# --- Default Interface Configuration ---
interfaces:
  - name: "wan1"
    description: "Primary Internet"
    # The IP address is usually set via DHCP or in the specific device file
    ip_address: "192.168.1.2"
    subnet_mask: "255.255.255.0"
    allowaccess:
      - "ping"
      - "https"
      - "ssh"

  - name: "internal"
    description: "Internal LAN"
    ip_address: "10.10.10.1"
    subnet_mask: "255.255.255.0"
    allowaccess:
      - "ping"
      - "https"
      - "ssh"

  - name: "dmz"
    description: "DMZ Network"
    ip_address: "172.16.1.1"
    subnet_mask: "255.255.255.0"
    allowaccess:
      - "ping"

# --- Default Zone Configuration ---
zones:
  - name: "untrust"
    interfaces:
      - "wan1"
  - name: "trust"
    interfaces:
      - "internal"
  - name: "dmz"
    interfaces:
      - "dmz"

# --- Default Address Objects ---
firewall_addresses:
  - name: "RFC1918-10.0.0.0"
    subnet: "10.0.0.0 255.0.0.0"
  - name: "RFC1918-172.16.0.0"
    subnet: "172.16.0.0 255.240.0.0"
  - name: "RFC1918-192.168.0.0"
    subnet: "192.168.0.0 255.255.0.0"
  - name: "ALL" # FortiGate's default object for 0.0.0.0/0
    subnet: "0.0.0.0 0.0.0.0"

# --- Default Static Route (Default Route) ---
static_routes:
  - gateway: "192.168.1.1" # Gateway IP for the WAN interface
    device: "wan1"

# --- Default Firewall Policies ---
firewall_policies:
  - id: 1
    name: "LAN-to-WAN"
    srcintf:
      - "internal"
    dstintf:
      - "wan1"
    srcaddr:
      - "RFC1918-10.0.0.0"
    dstaddr:
      - "ALL"
    action: "accept"
    service:
      - "ALL"
    nat: true

  - id: 2
    name: "DMZ-to-WAN"
    srcintf:
      - "dmz"
    dstintf:
      - "wan1"
    srcaddr:
      - "RFC1918-172.16.0.0"
    dstaddr:
      - "ALL"
    action: "accept"
    service:
      - "HTTP"
      - "HTTPS"
      - "DNS"
    nat: true

  - id: 10
    name: "Default-Deny"
    srcintf:
      - "any"
    dstintf:
      - "any"
    srcaddr:
      - "ALL"
    dstaddr:
      - "ALL"
    action: "deny"
    service:
      - "ALL"
    nat: false
